### ISSUE TITLE
Multiple death types show an error in console, and nothing in game chat.

### ISSUE THREAD

**Issue by Ejraiel** [SurvivorCDG/Advanced-Death-Messages#1]
When players bleed to death, an error is shown in the console, and no alert is shown in chat.

![bleeding](https://cloud.githubusercontent.com/assets/17344624/13798927/0cec712c-ead8-11e5-9f08-06fa26baf368.png)

Actually, this happens with other death types too, such as suffocation and death by zombie.

![suffocation and zombie too](https://cloud.githubusercontent.com/assets/17344624/13798972/76e608b8-ead8-11e5-8a22-ba0361dc498d.png)

**I can confirm that the following death types work fine:**
- _Being shot to death._
- _Being run over by a vehicle currently driven/piloted by a player._
- _Being "shredded to death" by a trap._
- _Melee weapons_
- _Punching_
- _/kill command_

**I can confirm that these death types cause errors and show no death message:**
- _Bleeding_
- _Suffocation_
- _Zombie attack_
- _Grenade explosion_
- _Vehicle explosion_
- _Burning_
- _Landmine_
- _Falling_
- _Infection_
- _Dehydration_

 
 
**Versions:**
Unturned 3.14.8.1
Rocket 815 _(4.9.3.1)_ to 818 _(4.9.3.1)_
Advanced Death Messages 1.0.7.5

**Comment by surv0013** [comment]
Thx for help, fixed & closed.

**Comment by Ejraiel** [comment]
=]
