### ISSUE TITLE
It would be nice to be able to remove the "[Alert] Server: " part of every death message.

### ISSUE THREAD

**Issue by Ejraiel** [SurvivorCDG/Advanced-Death-Messages#2]
Perhaps via a new config entry, such as `<ShowServerAlert>false</ShowServerAlert>`. =]

 
 
I'd like to see:
_"Player1 shot Player2 in the head with a Colt!"_

Instead of:
_"[Alert] Server: Player1 shot Player2 in the head with a Colt!"_

**Comment by surv0013** [comment]
Sry, but this unreal... Maybe later.

**Comment by Ejraiel** [comment]
Aww. Must be part of Unturned that isn't covered in the Rocket API, I assume?

Thanks for the response. =]
