### ISSUE TITLE
Sentry Message not work

### ISSUE THREAD

**Issue by AlexNTFox** [SurvivorCDG/Advanced-Death-Messages#3]
I was not the first time confronted with such a problem. When a turret kills someone, she writes (1) (2) (3). Instead, she writes ??? ??? ???

Я уже не первый раз сталкиваюсь с такой проблемой. Когда турель убивает кого-то она не пишет (1) (2) (3). Вместо этого она пишет ??? ??? ???

**Comment by surv0013** [comment]
Пример стандартного сообщения: "_**Player** killed in the **???** by **???**'s turret_".

Дело в том, что если владелец турели отсутствует на сервере, то вместо его имени будет "???", по причине того, что его ник не определён. Ну а как известно, турель способна убивать и при отсутствии владельца на сервере, главное, чтобы было заряженное оружие и электро-питание.

Следовательно, это не совсем проблема, скорее некоторая недоработка. Можно конечно кэшировать ники владельцов турелей, но это может нагружать работу сервера, как вариант, можно записывать ники владельцев в документ.txt, и пока их турель есть на сервере, хранить их SteamID и последний записанный ник. Правда - это немного глупо.

Ну а баг с тем, что при отсутствии владельца, часть тела, в которую был убит игрок, также не отображается, я исправлю.

Конечный вариант сообщения: "_**Player** killed in the **body** by **???**'s turret_".

-Спасибо за помощь в развитии плагина-
